/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restaurant.views;

/**
 *
 * @author DELL
 */
public class MainView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(MainView.class.getName());

    /**
     * Creates new form MainView
     */
    public MainView() {
        initComponents();
        setTitle("Gestion de Restaurant");
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuProduit = new javax.swing.JMenuItem();
        jMenu2 = new javax.swing.JMenu();
        menuStock = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuCommande = new javax.swing.JMenuItem();
        jMenu4 = new javax.swing.JMenu();
        menuStatistique = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        menuQuitter = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jMenu1.setText("Produit");

        menuProduit.setText("Gérer les produits");
        menuProduit.addActionListener(this::menuProduitActionPerformed);
        jMenu1.add(menuProduit);

        jMenuBar1.add(jMenu1);

        jMenu2.setText("Stock");

        menuStock.setText("Mouvement de stock");
        menuStock.addActionListener(this::menuStockActionPerformed);
        jMenu2.add(menuStock);

        jMenuBar1.add(jMenu2);

        jMenu3.setText("Commande");

        menuCommande.setText("Nouvelle commande");
        menuCommande.addActionListener(this::menuCommandeActionPerformed);
        jMenu3.add(menuCommande);

        jMenuBar1.add(jMenu3);

        jMenu4.setText("Statistique");

        menuStatistique.setText("Voir statistiques");
        menuStatistique.addActionListener(this::menuStatistiqueActionPerformed);
        jMenu4.add(menuStatistique);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Quitter");

        menuQuitter.setText("Quitter l'application");
        menuQuitter.addActionListener(this::menuQuitterActionPerformed);
        jMenu5.add(menuQuitter);

        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 277, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void menuQuitterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuQuitterActionPerformed
        // TODO add your handling code here:
        System.exit(0);
    }//GEN-LAST:event_menuQuitterActionPerformed

    private void menuStatistiqueActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStatistiqueActionPerformed
        // TODO add your handling code here:
        new StatistiqueView().setVisible(true);
    }//GEN-LAST:event_menuStatistiqueActionPerformed

    private void menuCommandeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuCommandeActionPerformed
        // TODO add your handling code here:
        new CommandeView().setVisible(true);
    }//GEN-LAST:event_menuCommandeActionPerformed

    private void menuStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuStockActionPerformed
        // TODO add your handling code here:
        new StockView().setVisible(true);
    }//GEN-LAST:event_menuStockActionPerformed

    private void menuProduitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_menuProduitActionPerformed
        // TODO add your handling code here:
        new ProduitView().setVisible(true);
    }//GEN-LAST:event_menuProduitActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new MainView().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem menuCommande;
    private javax.swing.JMenuItem menuProduit;
    private javax.swing.JMenuItem menuQuitter;
    private javax.swing.JMenuItem menuStatistique;
    private javax.swing.JMenuItem menuStock;
    // End of variables declaration//GEN-END:variables
}
