/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.restaurant.views;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import java.util.Map;
import java.util.HashMap;



/**
 *
 * @author DELL
 */
public class StatistiqueView extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(StatistiqueView.class.getName());
    private DefaultTableModel modelTopProduits;


    /**
     * Creates new form StatistiqueView
     */
    public StatistiqueView() {
        initComponents();
        setTitle("Statistiques");
        setLocationRelativeTo(null);
        initialiserStats();
    }
    
    

    private String formatMontant(double montant) {
        return String.format("%,.0f FCFA", montant);
    }
    
    private double calculChiffreAffairesJour(LocalDate date) {
        //Données fictives pour le moment
        if (date.equals(LocalDate.now())) {
            return 45000;
        }
        return 0;
    }

    private double calculChiffreAffairesPeriode(LocalDate debut, LocalDate fin) {

        // Sécurité
        if (fin.isBefore(debut)) {
            return 0;
        }

        // ⚠️ Données fictives (temporaire)
        LocalDate aujourdHui = LocalDate.now();

        if (!aujourdHui.isBefore(debut) && !aujourdHui.isAfter(fin)) {
            return 145000;
        }

        return 0;
    }
    
    private Map<String, Integer,> calculTopProduits(LocalDate debut, LocalDate fin) {

        Map<String, Integer> resultats = new HashMap<>();

        // ⚠️ Données fictives
        resultats.put("Pizza", 35, 0, 5, "Rupture");
        resultats.put("Burger", 22, 3, 5, "Stock faible");
        resultats.put("Jus", 40, 0, 5, "Rupture");

        return resultats;
    }



    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblDate = new javax.swing.JLabel();
        lblResultatJour = new javax.swing.JLabel();
        btnActualiser = new javax.swing.JButton();
        btnfermer = new javax.swing.JButton();
        txtDateJour = new javax.swing.JTextField();
        btnCalculerJour = new javax.swing.JButton();
        txtDateDebut = new javax.swing.JTextField();
        txtDateFin = new javax.swing.JTextField();
        lblDateFin = new javax.swing.JLabel();
        lblResultatPeriode = new javax.swing.JLabel();
        btnCalculPeriode = new javax.swing.JButton();
        lblDateDebut = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tableTopProduits = new javax.swing.JTable();
        btnTopProduits = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnAlerteStock = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblDate.setText("Date :");

        lblResultatJour.setText("Info important");

        btnActualiser.setText("Actualiser");
        btnActualiser.addActionListener(this::btnActualiserActionPerformed);

        btnfermer.setText("Fermer");
        btnfermer.addActionListener(this::btnfermerActionPerformed);

        txtDateJour.setText("jTextField1");

        btnCalculerJour.setText("Calculer");
        btnCalculerJour.addActionListener(this::btnCalculerJourActionPerformed);

        txtDateDebut.setText("jTextField1");

        txtDateFin.setText("jTextField1");

        lblDateFin.setText("Date fin :");

        lblResultatPeriode.setText("CA période : 0 FCFA");

        btnCalculPeriode.setText("Calculer");
        btnCalculPeriode.addActionListener(this::btnCalculPeriodeActionPerformed);

        lblDateDebut.setText("Date début :");

        tableTopProduits.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Produit", "Quantite vendue", "Stock", "Seuil", "Etat"
            }
        ));
        jScrollPane1.setViewportView(tableTopProduits);

        btnTopProduits.setText("Afficher");
        btnTopProduits.addActionListener(this::btnTopProduitsActionPerformed);

        jLabel1.setText("Alerte Stock :");

        btnAlerteStock.setText("Afficher");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(btnCalculerJour))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(20, 20, 20)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(lblDate, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(41, 41, 41)
                                    .addComponent(txtDateJour, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(lblResultatJour, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblDateDebut)
                                    .addComponent(lblDateFin))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(lblResultatPeriode, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnActualiser)
                                .addGap(18, 18, 18)
                                .addComponent(btnfermer))
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(46, 46, 46)
                        .addComponent(btnCalculPeriode))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(70, 70, 70)
                        .addComponent(btnTopProduits)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addComponent(btnAlerteStock)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(11, 11, 11)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblDate)
                            .addComponent(txtDateJour, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnCalculerJour)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lblResultatJour)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateDebut)
                            .addComponent(txtDateDebut, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblDateFin)
                            .addComponent(txtDateFin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(btnCalculPeriode)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lblResultatPeriode)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnActualiser)
                            .addComponent(btnfermer))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnTopProduits))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(btnAlerteStock)
                .addContainerGap(44, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnActualiserActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        initialiserStats();
    }                                             

    private void initialiserStats() {

        // Valeurs par défaut à l'ouverture
        lblResultatJour.setText("CA du jour : 0 FCFA");
        lblResultatPeriode.setText("CA période : 0 FCFA");

        // Optionnel : dates par défaut
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        String aujourdHui = LocalDate.now().format(formatter);

        txtDateJour.setText(aujourdHui);
        txtDateDebut.setText(aujourdHui);
        txtDateFin.setText(aujourdHui);
        
        modelTopProduits = new DefaultTableModel(
        new Object[]{"Produit", "Quantité vendue",  "Stock", "Seuil", "État"}, 0
    );
    tableTopProduits.setModel(modelTopProduits);

}

    
    private void btnfermerActionPerformed(java.awt.event.ActionEvent evt) {                                          
        // TODO add your handling code here:
         this.dispose();
    }                                         

    private void btnCalculerJourActionPerformed(java.awt.event.ActionEvent evt) {                                                
        // TODO add your handling code here:
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
            LocalDate date = LocalDate.parse(txtDateJour.getText(), formatter);

            double ca = calculChiffreAffairesJour(date);
            lblResultatJour.setText("CA du jour : " + formatMontant(ca));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Date invalide (dd/MM/yyyy)");
        }
    }                                               

    private void btnCalculPeriodeActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        // TODO add your handling code here:
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            LocalDate debut = LocalDate.parse(txtDateDebut.getText(), formatter);
            LocalDate fin = LocalDate.parse(txtDateFin.getText(), formatter);

            if (fin.isBefore(debut)) {
                JOptionPane.showMessageDialog(this, "La date de fin doit être après la date de début");
                return;
            }

            double ca = calculChiffreAffairesPeriode(debut, fin);
            lblResultatPeriode.setText("CA période : " + formatMontant(ca));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dates invalides (dd/MM/yyyy)");
        }
    }                                                

    private void btnTopProduitsActionPerformed(java.awt.event.ActionEvent evt) {                                               
        // TODO add your handling code here:
        try {
            DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");

            LocalDate debut = LocalDate.parse(txtDateDebut.getText(), formatter);
            LocalDate fin = LocalDate.parse(txtDateFin.getText(), formatter);

            modelTopProduits.setRowCount(0);

            Map<String, Integer> top = calculTopProduits(debut, fin);

            top.entrySet().stream()
                .sorted(Map.Entry.<String, Integer>comparingByValue().reversed())
                .forEach(e -> modelTopProduits.addRow(
                    new Object[]{e.getKey(), e.getValue()}
                ));

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Dates invalides");
        }
    }                                              

    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(() -> {
            new StatistiqueView().setVisible(true);
        });
        java.awt.EventQueue.invokeLater(() -> new StatistiqueView().setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnActualiser;
    private javax.swing.JButton btnAlerteStock;
    private javax.swing.JButton btnCalculPeriode;
    private javax.swing.JButton btnCalculerJour;
    private javax.swing.JButton btnTopProduits;
    private javax.swing.JButton btnfermer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblDate;
    private javax.swing.JLabel lblDateDebut;
    private javax.swing.JLabel lblDateFin;
    private javax.swing.JLabel lblResultatJour;
    private javax.swing.JLabel lblResultatPeriode;
    private javax.swing.JTable tableTopProduits;
    private javax.swing.JTextField txtDateDebut;
    private javax.swing.JTextField txtDateFin;
    private javax.swing.JTextField txtDateJour;
    // End of variables declaration                   
}